name: Deploy CocoaPods

on:
  push:
    tags:
      - '*'

jobs:
  push:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Cocoapods
        run: gem install cocoapods

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod trunk push --allow-warnings NuguUtils.podspec
          pod trunk push --synchronous --allow-warnings NuguCore.podspec
          pod trunk push --synchronous --allow-warnings JadeMarble.podspec
          pod trunk push --synchronous --allow-warnings SilverTray.podspec
          pod trunk push --synchronous --allow-warnings NuguAgents.podspec
          pod trunk push --synchronous --allow-warnings NuguServiceKit.podspec
          pod trunk push --synchronous --allow-warnings NuguUIKit.podspec
          pod trunk push --synchronous --allow-warnings NuguLoginKit.podspec
          pod trunk push --synchronous --allow-warnings KeenSense.podspec
          pod trunk push --synchronous --allow-warnings NuguClientKit.podspec

        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
